### ISSUE TITLE
[question] npm-package and future plans

### ISSUE THREAD

**Issue by earloc** [jmcdo29/nestjs-spelunker#19]
hey there!

Nice work you´ve done so far with this little thingy, here. I have some questions, however:
1. Is this still maintained and are you still interrested in doing so?
2. Are you planning to publish this as a npm-package for better consumption in existing projects?
3. I tinkered around with the bits provided here and prototyped an approach to visualize the dependency-graph utilizing [structurizr](https://structurizr.com/help/lite). Are you interrested in PR´s?
![image](https://user-images.githubusercontent.com/8486862/158129004-3da3030d-240e-4fb9-9a59-160deb68b31a.png)

**Comment by jmcdo29** [comment]
Something to bring up, Nest v8 changed the injection token form. In Nest's own instance loader logger, we shorten the token to just the class name, if it is a class in the first place. Should we do that here too? Otherwise at the very least we'll see tokens like this:
```ts
class·DogsService·{\n}
```
And at the worst we'll see some like this:
```ts
class·RpcInterceptorService·extends·abstract_interceptor_service_1.AbstractInterceptorService·{\n····getCallPoint(context)·{\n········return·this.reflector.get('microservices:pattern',·context.getHandler());\n····}\n····/**\n·····*·A·helper·method·to·get·the·appropriate·data·object·for·the·adapter\n·····*·@param·context·execution·context·from·Nest\n·····*·@returns·The·data·object·for·the·RPC·adapter\n·····*/\n····getData(context)·{\n········return·context.switchToRpc().getData();\n····}\n····/**\n·····*·A·helper·method·to·get·the·RPC·client·from·the·execution·context\n·····*·@param·context·execution·context·from·Nest\n·····*·@returns·The·client·object·for·the·RPC·adapter\n·····*/\n····getClient(context)·{\n········return·context.switchToRpc().getContext();\n····}\n}
```
(Yes, that is a single token)

We could just get the class name and extra metadata somehow to say "Hey, this is a shortened version of the token" or something . Thoughts?

**Comment by earloc** [comment]
wouldn´t this topic be another issue? ;D

But yeah, sounds like a ood idea to shorten the `InjetionToken` into such a form. I think the above examples should produce
`DogsService` and `RpcInterceptionService`.

**Comment by jmcdo29** [comment]
Okay, nestjs-spelunker v1 was just published. README has been updated, and there are now more tests for circular dependencies. All in All it should be usable with Nest v8
