### ISSUE TITLE
Thanks and feedback

### ISSUE THREAD

**Issue by JorgeLGonzalez** [jmcdo29/nestjs-spelunker#24]
Mainly wanted to thank you for this package as I just used it to great benefit. Was looking to quickly generate a visual graph of the module dependencies in our project and stumbled on this. Didn't quite do what I needed, but it was a nice stepping stone. I was able to create a proper graph data structure and then generate a mermaid diagram to visualize and then simplify the dependencies. Not sure if you were interested to go in that direction, but happy to discuss more if you are.

**Comment by jmcdo29** [comment]
Are there changes that need to be made to the returned data structure? I'd be more then happy to improve this in terms of data output and then have integrable libraries that take in the data structure and print something visual

**Comment by JorgeLGonzalez** [comment]
No changes needed, but it would require an additional data structure and code to build it from SpelunkedTree[]. Here's the structure I used:
`export interface IModuleGraphNode {
  dependencies: Set<IModuleGraphNode>;
  dependents: Set<IModuleGraphNode>;
  module: SpelunkedTree;
}`

Once you have that, it's pretty trivial to traverse it. To generate a [mermaid](https://mermaid-js.github.io/mermaid/#/) graph, for example, its just a matter of generating the edges.  Happy to share some code and ideas.

**Comment by JorgeLGonzalez** [comment]
Here's a possible approach:

1. Add `GraphingModule.graph(tree: SpelunkedTree[]): GraphNode`
2. `GraphNode` looks like this:
```
export interface GraphNode {
  dependences: Set<GraphNode>;
  dependents: Set<GraphNode>;
  module: SpelunkedTree;
}
```
3. Add `GraphingModule.writeMermaidGraph(filePath: string, root: GraphNode, options?: MermaidGraphOptions): void`. 
4. This would write a markdown file with a simple [mermaid LR graph](https://mermaid-js.github.io/mermaid/#/examples?id=basic-flowchart). The options can be used to, for example, exclude certain modules, short-circuit circular dependencies, and control details of the mermaid syntax

There's nothing special about mermaid. I just had used it before and its trivial to create a simple graph. Given the GraphNode, exporting to other syntax would be only as complicated as that syntax is. Can leave Mermaid out for now, or put it in a separate module. Happy to help with code.

In my case, I was able to generate a graph of the app we're building and then rationalize the dependencies so as to simplify them. Here's how the graph ended up: 
![modedeps-after](https://user-images.githubusercontent.com/8647849/162578603-afbd5525-7b8c-4d43-a6a3-a5677953c0aa.png)

**Comment by jmcdo29** [comment]
The output here looks pretty awesome and very much what I was hoping people would do with this library to be honest! I'd love to see this turned into a community module and link to it from the README as an example of what could be done with the output.

I'm hesitant to add in a dedicated rendering library as I'd like `nestjs-spelunker` to be as barebones and integratable as possible, but I do love to see integrations like this. 

You said there's no real changes that need to be made to this library right, just that you needed to modify the data structure specifically for the rendering, correct?

**Comment by JorgeLGonzalez** [comment]
Gotcha. The integration to mermaid is absolutely minimal, but I hear what you're saying. I created a [PR](https://github.com/jmcdo29/nestjs-spelunker/pull/25) to clarify the suggestion and eliminate even a conceptual dependency to Mermaid or any other renderer.
