### ISSUE TITLE
Doesn't output anything.

### ISSUE THREAD

**Issue by MattGson** [jmcdo29/nestjs-spelunker#29]
I have hooked into the app as specified. App starts up as normal but nothing new is logged.

```
	const app = await NestFactory.create<NestExpressApplication>(AppModule, {
		bodyParser: false
	});

...

        SpelunkerModule.explore(app);
        await app.listen(envs.port || 3000);

```

There is no output log?

**Comment by jmcdo29** [comment]
Looks like I need to update the readme. You can wrap the `SpelunkerModule.explore` in a `console.log` to see the output

**Comment by MattGson** [comment]
Thanks, that was it
