### ISSUE TITLE
Import tree is incorrect

### ISSUE THREAD

**Issue by MattGson** [jmcdo29/nestjs-spelunker#30]
The generated import tree is very wrong for my app.

It shows lots of modules importing their parent and sibling modules.

This includes every module importing the root AppModule.

**Comment by jmcdo29** [comment]
Oh that's interesting. Got this in a minimum reproduction?

**Comment by jmcdo29** [comment]
I'm going to close this due to inactivity. If you can provide a reproduction I'll be happy to take a look
