### ISSUE TITLE
Docs improvement: add the source code of the sample output

### ISSUE THREAD

**Issue by micalevisk** [jmcdo29/nestjs-spelunker#34]
I believe it would be helpful if we have the source code (only the files, not the project itself) used to get the sample ouptut (https://github.com/jmcdo29/nestjs-spelunker#exploration-sample-output)

Maybe hidden inside of `<details></details>` like so:

<details>
<summary>Demo code</summary>

```ts
// foo.service.ts
export class FooService {}
```

</details>

**Comment by micalevisk** [comment]
Also, we should update the following

![image](https://user-images.githubusercontent.com/13461315/198890408-0a254486-b9f1-4ccd-9c08-ece258802776.png)

as that module no longer outputs anything

**Comment by jmcdo29** [comment]
Yeah, to be honest, this project needs a bit of love an attention from me. Once I get some more time I'll get back into the cleanup :smile:
