### ISSUE TITLE
FR: Excluding modules

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [jmcdo29/nestjs-spelunker#38]
I think it might be useful to have an exclude option for module name.
I know, it is possible to just adjust the map function to filter out those, but anyway, for usability :D.

For example there is a lot of clutter if you have TypeOrmModule or ConfigModule around because a lot of modules will point at those.

**Comment by jmcdo29** [comment]
Maybe like an `ignoreImportsRegex`? Or maybe an array that checks substrings

**Comment by sschneider-ihre-pvs** [comment]
by pattern or by module.name or so yes
