### ISSUE TITLE
Change param type explore from INestApplication to INestApplicationContext

### ISSUE THREAD

**Issue by fjodor-rybakov** [jmcdo29/nestjs-spelunker#5]
Function `explore` work only for `INestApplication`, but not work with `INestApplicationContext`. Need change param type for `explore` from `INestApplication` to `INestApplicationContext`. Please fix it!
"nestjs-spelunker": "^0.2.0"

**Comment by jmcdo29** [comment]
I can get this fixed soon, or you're welcome to raise a PR. Until the new version is published you can use `as any` or `as unknown`

**Comment by fjodor-rybakov** [comment]
@jmcdo29 PR https://github.com/jmcdo29/nestjs-spelunker/pull/6

**Comment by jmcdo29** [comment]
Fixed by #6. Published in 0.2.1
