### ISSUE TITLE
Excluded modules are still being shown in the imports array

### ISSUE THREAD

**Issue by klu2** [jmcdo29/nestjs-spelunker#56]
With https://github.com/jmcdo29/nestjs-spelunker/issues/38 the option to [exclude modules](https://github.com/jmcdo29/nestjs-spelunker?tab=readme-ov-file#excluding-modules) was implemented, which is a great thing!

Suppose I have the following code

```typescript
const tree = SpelunkerModule.explore(app,{
    ignoreImports: [
        (moduleName) => moduleName === 'GoogleRecaptchaModules',
    ],        
});
````

Then the `GoogleRecaptchaModule` is not listed anymore in the `tree` elements (which is good), but it is still shown is `import` for all other modules, i.e.

```
  {
    name: 'MyOtherModule',
    imports: [
      'GoogleRecaptchaModule',
      'ConfigHostModule',
    ],
    providers: {},
    controllers: [],
    exports: []
  },
```

If you feed such a tree to `SpelunkerModule.graph(tree)` you get an exception as of the missing `GoogleRecaptchaModule`.

I therefore believe that if a module is excluded with `ignoreImports`, it should also not be displayed any longer inside the `imports` of the resulting `tree`.

**Comment by micalevisk** [comment]
@jmcdo29 what do you think about this? I believe that introducing this would be a breaking change but I like this ideia

**Comment by jmcdo29** [comment]
This sounds like a bug to me, and something they should be pretty easy to fix. I'll see if in can start working on that next week
